# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    #- docker login -u "yugesh_ganesan" --password-stdin "756446@YUg" sample-project
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #- docker login registry.gitlab.com -u yugesh_ganesan -p 1cFxpyJzw5S5R7ospvVM
    #- docker login registry.gitlab.com
  script:
    #- docker build --pull -t "$CI_REGISTRY_IMAGE" .
    #- docker push "$CI_REGISTRY_IMAGE"
    - $ImageUri = registry.gitlab.com/yugesh_ganesan/sample-project:"$CI_PIPELINE_IID"
    - docker build -t "$ImageUri" .
    - docker push $ImageUri"
  only:
    - master
