apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
  namespace: python-web
  labels:
    app: python-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web
  strategy: {}
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: registry.gitlab.com/yugesh_ganesan/sample-project:master
        imagePullPolicy: Always
        env:
        - name: FOR REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        ports:
          - containerPort: 8080
        resources: {}
      imagePullSecrets:
      - name: gitlab-auth
